# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/blog',
                'doc_host': 'https://gkteco.github.io',
                'git_url': 'https://github.com/gkteco/blog',
                'lib_path': 'blog'},
  'syms': {'blog.DataBlockWalkthrough': {}}}
